"""Added account table

Revision ID: 4a61cbf0877e
Revises: 1cca555484a7
Create Date: 2020-01-07 20:25:12.420707

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a61cbf0877e'
down_revision = '1cca555484a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('best_moves',
                    sa.Column('best_move_id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'),
                              autoincrement=False, nullable=False),
                    sa.Column('game_id', postgresql.UUID(), autoincrement=False, nullable=False),
                    sa.Column('killed_house', postgresql.UUID(), autoincrement=False, nullable=True),
                    sa.Column('best_1', postgresql.UUID(), autoincrement=False, nullable=True),
                    sa.Column('best_2', postgresql.UUID(), autoincrement=False, nullable=True),
                    sa.Column('best_3', postgresql.UUID(), autoincrement=False, nullable=True),

                    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], name='houses_game_id_fkey'),
                    sa.ForeignKeyConstraint(['killed_house'], ['houses.house_id'], name='houses_killed_house_fkey'),
                    sa.ForeignKeyConstraint(['best_1'], ['houses.house_id'], name='houses_best_1_fkey'),
                    sa.ForeignKeyConstraint(['best_2'], ['houses.house_id'], name='houses_best_2_fkey'),
                    sa.ForeignKeyConstraint(['best_3'], ['houses.house_id'], name='houses_best_3_fkey'),

                    sa.PrimaryKeyConstraint('best_move_id', name='best_moves_pkey')
                    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("")

    # ### end Alembic commands ###
