"""empty message

Revision ID: 85e2fd6720da
Revises: d48548d1942e
Create Date: 2020-01-24 21:03:48.740897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85e2fd6720da'
down_revision = 'd48548d1942e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('best_moves', 'game_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'best_moves', ['game_id'])
    op.alter_column('games', 'heading',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('games', 'result',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('games', 'tournament',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('houses', 'game_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('houses', 'player_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('houses', 'role',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('houses', 'slot',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('houses', 'slot',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('houses', 'role',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('houses', 'player_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('houses', 'game_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('games', 'tournament',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('games', 'result',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('games', 'heading',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_constraint(None, 'best_moves', type_='unique')
    op.alter_column('best_moves', 'game_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
