"""Add Voted and Nominated for Best

Revision ID: ff4145c5a4a6
Revises: cdf9b654ec97
Create Date: 2020-10-04 23:12:11.958508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff4145c5a4a6'
down_revision = 'cdf9b654ec97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nominated_for_best',
    sa.Column('nominated_for_best_id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('game_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('house', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['house'], ['houses.house_id'], ),
    sa.PrimaryKeyConstraint('nominated_for_best_id')
    )
    op.create_table('voted',
    sa.Column('voted_id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('game_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('voted_house_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('voted_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['voted_house_id'], ['houses.house_id'], ),
    sa.PrimaryKeyConstraint('voted_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voted')
    op.drop_table('nominated_for_best')
    # ### end Alembic commands ###
