version: '3.1'

services:

  zlodb:
    image: postgres
    restart: always
    hostname: zlodb
    container_name: zlodb
    env_file:
      - .env
    ports:
      - "5432:5432"

  test_zlo_db:
    image: postgres
    restart: always
    hostname: test_zlo_db
    container_name: test_zlo_db
    env_file:
      - test.env
    ports:
      - "5432:8001"

