BONUS_FOR_2_GUESS_MAFIA_IN_BEST_MOVE = 1
BONUS_FOR_3_GUESS_MAFIA_IN_BEST_MOVE = 2
BONUS_FOR_SHERIFF_PLAY = 1
BONUS_FOR_MISS_FROM_MAFIA = -3
BONUS_FOR_PLAYING_LIKE_SHERIFF = 1
BONUS_FOR_VOTED_THREE_CITIZEN_TO_MAFIA = 2
BONUS_FOR_VOTED_THREE_CITIZEN_TO_CITIZEN = -2
