# Three voted
CORRELATION_FOR_VOTED_THREE_CITIZEN_TO_CITIZEN = -2
BONUS_FOR_VOTED_THREE_CITIZEN_TO_MAFIA = 2

# Disqualifiled
CORRELATION_FOR_DISQUALIFIELD_PLAYER = -5

# Best move
BONUS_FOR_2_GUESS_MAFIA_IN_BEST_MOVE = 1
BONUS_FOR_3_GUESS_MAFIA_IN_BEST_MOVE = 2

# Hand of Mafia
CORRELATION_FOR_BEING_HAND_OF_MAFIA = -2

# Miss
CORRELATION_FOR_MISS_FROM_MAFIA = -3

# Sheriff version
BONUS_FOR_PLAYING_LIKE_SHERIFF = 1

# Devises
BIG_BONUS_FOR_CORRECT_DEVISE_FOR_3 = 4
BIG_BONUS_FOR_CORRECT_DEVISE_FOR_2 = 3
BIG_BONUS_FOR_CORRECT_DEVISE_FOR_1 = 2
BIG_CORRELATION_FOR_WRONG_DEVISE_FOR_3 = -4
BIG_CORRELATION_FOR_WRONG_DEVISE_FOR_2 = -3
BIG_CORRELATION_FOR_WRONG_DEVISE_FOR_1 = -2

LOW_BONUS_FOR_CORRECT_DEVISE_FOR_3 = 3
LOW_BONUS_FOR_CORRECT_DEVISE_FOR_2 = 2
LOW_BONUS_FOR_CORRECT_DEVISE_FOR_1 = 1
LOW_CORRELATION_FOR_WRONG_DEVISE_FOR_3 = -3
LOW_CORRELATION_FOR_WRONG_DEVISE_FOR_2 = -2
LOW_CORRELATION_FOR_WRONG_DEVISE_FOR_1 = -1

# Breaks
CORRELATION_FOR_WRONG_BREAK = -3

# Bonuses from heading
MIDDLE_BONUS_FROM_HEADING = 2
HIGH_BONUS_FROM_HEADING = 3
LOW_BONUS_FROM_HEADING = 1

# Sheriff play
BONUS_FOR_SHERIFF_PLAY = 1

# Best player
BONUS_FOR_BEST_PLAYER = 1
