"""сreate_tables

Revision ID: 1cca555484a7
Revises: 
Create Date: 2019-10-16 19:01:57.091851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from uuid import uuid4

# revision identifiers, used by Alembic.
revision = '1cca555484a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    connection = op.get_bind()
    connection.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('player_id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('nickname', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('club', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('player_id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('positions',
    sa.Column('position_id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('player_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('role', sa.Enum('citizen', 'mafia', 'sheriff', 'don', name='role'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_table('don_checks',
    sa.Column('vote_expose_id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('night', sa.Integer(), nullable=False),
    sa.Column('target', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['target'], ['positions.position_id'], ),
    sa.PrimaryKeyConstraint('vote_expose_id')
    )
    op.create_table('sheriff_checks',
    sa.Column('sheriff_check_id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('night', sa.Integer(), nullable=False),
    sa.Column('target', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['target'], ['positions.position_id'], ),
    sa.PrimaryKeyConstraint('sheriff_check_id')
    )
    op.create_table('shots',
    sa.Column('shot_id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('night', sa.Integer(), nullable=False),
    sa.Column('shooter', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('target', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['shooter'], ['positions.position_id'], ),
    sa.ForeignKeyConstraint(['target'], ['positions.position_id'], ),
    sa.PrimaryKeyConstraint('shot_id')
    )
    op.create_table('votes',
    sa.Column('vote_id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('revote', sa.Integer(), nullable=False),
    sa.Column('source_pos', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('target_pos', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['source_pos'], ['positions.position_id'], ),
    sa.ForeignKeyConstraint(['target_pos'], ['positions.position_id'], ),
    sa.PrimaryKeyConstraint('vote_id')
    )
    op.create_table('votes_exposes',
    sa.Column('vote_expose_id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('game_id', sa.String(length=50), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('revote', sa.Integer(), nullable=False),
    sa.Column('source_pos', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('target_pos', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['source_pos'], ['positions.position_id'], ),
    sa.ForeignKeyConstraint(['target_pos'], ['positions.position_id'], ),
    sa.PrimaryKeyConstraint('vote_expose_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes_exposes')
    op.drop_table('votes')
    op.drop_table('shots')
    op.drop_table('sheriff_checks')
    op.drop_table('don_checks')
    op.drop_table('positions')
    op.drop_table('players')
    # ### end Alembic commands ###
