"""Add not null club and fix names

Revision ID: 2dcbc6f987e8
Revises: 0bc99e8caf95
Create Date: 2021-08-29 14:55:03.922470

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.orm import Session

from dim_mafii.domain.model import Game, Rating

# revision identifiers, used by Alembic.
revision = '2dcbc6f987e8'
down_revision = '0bc99e8caf95'
branch_labels = None
depends_on = None


Club = sa.sql.table(
    'clubs',
    sa.Column(
        'name',
        sa.String(),
        nullable=False,
        unique=True
    )
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'games',
        'club',
        existing_type=sa.VARCHAR(length=40),
        nullable=False
    )
    session = Session(bind=op.get_bind())

    # Conflict-free updates without any links
    op.drop_constraint('fk_clubname_for_games', 'games', type_="foreignkey")
    op.drop_constraint('fk_clubname_for_rating', 'rating', type_="foreignkey")

    op.execute("TRUNCATE clubs")

    op.bulk_insert(Club, [{'name': name} for name in ('Дім Мафії', 'Школа Мафії')])

    # Update club's names in games
    with session.begin(subtransactions=True):
        for game in session.query(Game).all():
            if game.club == 'ZLO':
                game.club = 'Дім Мафії'
            if game.club == 'Школа Зло':
                game.club = 'Школа Мафії'

        for rating in session.query(Rating).all():
            if rating.club == 'ZLO':
                rating.club = 'Дім Мафії'
            if rating.club == 'Школа Зло':
                rating.club = 'Школа Мафії'

    # RETURN all links that we need
    op.create_foreign_key(
        'fk_clubname_for_rating',
        'rating',
        'clubs',
        local_cols=['club'],
        remote_cols=['name'],
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_clubname_for_games',
        'games',
        'clubs',
        local_cols=['club'],
        remote_cols=['name'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'games',
        'club',
        existing_type=sa.VARCHAR(length=40),
        nullable=True
    )
    session = Session(bind=op.get_bind())

    # Conflict-free updates without any links
    op.drop_constraint('fk_clubname_for_games', 'games', type_="foreignkey")
    op.drop_constraint('fk_clubname_for_rating', 'rating', type_="foreignkey")

    op.execute("TRUNCATE clubs")

    op.bulk_insert(Club, [{'name': name} for name in ('ZLO', 'Школа Зло')])

    with session.begin(subtransactions=True):
        for game in session.query(Game).all():
            if game.club == 'Дім Мафії':
                game.club = 'ZLO'
            if game.club == 'Школа Мафії':
                game.club = 'Школа Зло'

        for rating in session.query(Rating).all():
            if rating.club == 'Дім Мафії':
                rating.club = 'ZLO'
            if rating.club == 'Школа Мафії':
                rating.club = 'Школа Зло'

    # RETURN all links that we need
    op.create_foreign_key(
        'fk_clubname_for_rating',
        'rating',
        'clubs',
        local_cols=['club'],
        remote_cols=['name'],
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_clubname_for_games',
        'games',
        'clubs',
        local_cols=['club'],
        remote_cols=['name'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###
