"""Add not nullable values

Revision ID: 2dcbc6f987e8
Revises: 0bc99e8caf95
Create Date: 2021-08-29 14:55:03.922470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dcbc6f987e8'
down_revision = '0bc99e8caf95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'club',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'club',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###
